# Generated by Django 3.0 on 2019-12-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=15, help_text='Latitude coordinate of sighting', max_digits=20)),
                ('Longitude', models.DecimalField(decimal_places=15, help_text='Longitude coordinate of sighting', max_digits=20)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique ID of squirrel sighting', max_length=14)),
                ('Hectare', models.CharField(max_length=3)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Morning/Evening sighting', max_length=2)),
                ('Date', models.DateField(help_text='Date of sighting')),
                ('Hectare_Squirrel_Number', models.IntegerField()),
                ('Age', models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('JUVENILE', 'JUVENILE')], help_text='Age of squirrel sighted', max_length=10, null=True)),
                ('Primary_fur_color', models.CharField(blank=True, choices=[('GRAY', 'GRAY'), ('CINAMMON', 'CINNAMON'), ('BLACK', 'BLACK')], help_text='Color of the squirrel', max_length=20)),
                ('Highlight_fur_color', models.CharField(blank=True, help_text='Highlight color of the fur of the squirrel', max_length=50)),
                ('Combination_of_primary_and_highlight_color', models.CharField(blank=True, max_length=70)),
                ('Color_notes', models.CharField(blank=True, max_length=100)),
                ('Location', models.CharField(blank=True, choices=[('GROUND PLANE', 'GROUND PlANE'), ('ABOVE GROUND', 'ABOVE GROUND')], max_length=20)),
                ('Above_ground_sighter_measurement', models.CharField(blank=True, max_length=10)),
                ('Specific_location', models.CharField(blank=True, help_text='Location of sighting', max_length=40)),
                ('Running', models.BooleanField(default=False, help_text='True if squirrel seen running')),
                ('Chasing', models.BooleanField(default=False, help_text='True if squirrel was seen chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='True if Squirrel was seen climbing')),
                ('Eating', models.BooleanField(default=False, help_text='True if Squirrel is eating')),
                ('Foraging', models.BooleanField(default=False, help_text='True if Squirrel is foraging')),
                ('Other_activities', models.CharField(blank=True, help_text='Activity the Squirrel is performing', max_length=100)),
                ('kuks', models.BooleanField(default=False, help_text='True if the Squirrel is kuking - a chirpy voice communication')),
                ('quaas', models.BooleanField(default=False, help_text='True if the Squirrel is Quaaing - an elongated vocal call')),
                ('moans', models.BooleanField(default=False, help_text='True if the Squirrel is Moaning - a high pitched vocal communication')),
                ('tail_flags', models.BooleanField(default=False, help_text='True if the Squirrel is flagging its tail')),
                ('tail_twitches', models.BooleanField(default=False, help_text='True if the Squirrel is twitching its tail')),
                ('approaches', models.BooleanField(default=False, help_text='True if the Squirrel is seen approaching humans')),
                ('indifferent', models.BooleanField(default=False, help_text='True if squirrel was indifferent to humans')),
                ('runs_from', models.BooleanField(default=False, help_text='True if Squirrel was seen running from humans')),
                ('other_interactions', models.CharField(blank=True, max_length=100, null=True)),
                ('lat_Long', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6, null=True)),
                ('community_district', models.IntegerField()),
                ('borough_boundaries', models.IntegerField()),
                ('city_council_districts', models.IntegerField()),
                ('police_precincts', models.IntegerField()),
            ],
        ),
    ]
